### ISSUE TITLE
现阶段计划是在哈尔生日发布0.1版（赛叔线）

### ISSUE THREAD

**Issue by zhuty18** [zhuty18/EmeraldKnight#1]

**Comment by RoxanneRR** [comment]
加油姐妹wwww 现在是框架做完了还没写剧情吗

**Comment by zhuty18** [comment]
> 
> 
> 加油姐妹wwww 现在是框架做完了还没写剧情吗

唔，其实是这样的，赛叔那条线有比较多的R18内容，我写不下去，就先去写别的了。。。
现在第一章已经发布，总文本大概1.4w字，你感兴趣可以玩一下(〃'▽'〃)
